#### Regresie Logistica - Exemplu Bank Customer Data
Let's say i am data scientist working for the bank on a marketing campain. I need to predict which clients are more likely to accept the offer.

For now i will be able to test it by manually entering data into the table such as:
user1 = [0,1,0,1,0 # .....]
where 0 means is_married, 1 would be job_management or the other 0 would be is_fifties or is_fourties ...
It's always a good ideea to see on what to train and which is better

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pandas import Series, DataFrame
from sklearn.linear_model import LogisticRegression, LinearRegression
# gaussian naive bayes
from sklearn.naive_bayes import GaussianNB

Fisier CVS luat de pe UCI Machine Learning Repository (https://archive.ics.uci.edu/ml/datasets/Bank+Marketing#).



In [12]:
bank_full = pd.read_csv('bank_full_w_dummy_vars.csv')
bank_full.head()


age   job             marital    education   default   balance   housing   \
0    58  management      married    tertiary    no            2143  yes        
1    44  technician      single     secondary   no              29  yes        
2    33  entrepreneur    married    secondary   no               2  yes        
3    47  blue-collar     married    unknown     no            1506  yes        
4    33  unknown         single     unknown     no               1  no         

   loan   contact     day   ... job_unknown   job_retired   job_services   \
0  no     unknown        5  ...            0             0              0   
1  no     unknown        5  ...            0             0              0   
2  yes    unknown        5  ...            0             0              0   
3  no     unknown        5  ...            0             0              0   
4  no     unknown        5  ...            1             0              0   

   job_self_employed   job_unemployed  job_maid  job_student   married   \
0                   0                0         0            0         1   
1                   0                0         0            0         0   
2                   0                0         0            0         1   
3                   0                0         0            0         1   
4                   0                0         0            0         0   

   single   divorced  
0        0         0  
1        1         1  
2        0         0  
3        0         0  
4        1         1  

[5 rows x 37 columns]

The columns in the file 1-16 is the original data that came from marketing/bank. 
To apply our algorithm here we needed the data to have **binary values of 0s and 1s represented all the columns**.
So, **a little tinkering was involved :)**
That means after y, where col **y_binary** (our binary model), all columns have binary values that represent columns that would otherwise contain a string. for example " job == management (which is a string)" and would be represented as "job_management belongs to [0,1] where 0 == false and 1 == true " .... And the same for others where we have yes/no, we would still need true/false

In [13]:
bank_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   age                        45211 non-null  int64 
 1   job                        45211 non-null  object
 2   marital                    45211 non-null  object
 3   education                  45211 non-null  object
 4   default                    45211 non-null  object
 5   balance                    45211 non-null  int64 
 6   housing                    45211 non-null  object
 7   loan                       45211 non-null  object
 8   contact                    45211 non-null  object
 9   day                        45211 non-null  int64 
 10  month                      45211 non-null  object
 11  duration                   45211 non-null  int64 
 12  campaign                   45211 non-null  int64 
 13  pdays                      45211 non-null  int64 
 14  previo

In [14]:
X = bank_full.iloc[:, 18:37].values
y = bank_full.iloc[:, 17].values
y.view()


array([0, 0, 0, ..., 1, 0, 0])

In [15]:
LogReg = LogisticRegression()
xp = LogReg.fit(X, y)

# Gaussian Naive Bayes
gnb = GaussianNB()
y_pred = gnb.fit(X, y)

def test_model(model, X, y):
    model.fit(X, y)
    return model.score(X, y)

print(test_model(LogReg, X, y))
print(test_model(gnb, X, y))    

0.8930127623808365
0.8383358032337263


In [16]:
new_user = np.array([[0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1]])

def test_new_user(model, new_user, message="New user: "):
    y_pred = model.predict(new_user)
    y_pred_proba = model.predict_proba(new_user)
    print("\n")
    print(message)
    print("User will subscribe" if y_pred[0] == 1 else "User will not subscribe")
    print("Probability of subscribing: ", y_pred_proba[0][1], "\n")

print(test_new_user(LogReg, new_user, message="Logistic Regression"))
print(test_new_user(gnb, new_user, message="Gaussian Naive Bayes"))






Logistic Regression
User will not subscribe
Probability of subscribing:  0.03884038975628315 

None


Gaussian Naive Bayes
User will not subscribe
Probability of subscribing:  7.307563144007395e-11 

None


In [17]:
new_user = np.array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1]).reshape(1, -1)

test_new_user(LogReg, new_user, message="Logistic Regression")
test_new_user(gnb, new_user, message="Gaussian Naive Bayes")



Logistic Regression
User will subscribe
Probability of subscribing:  0.8946954120393635 



Gaussian Naive Bayes
User will subscribe
Probability of subscribing:  1.0 



In [18]:

# // show the confusion matrix
from sklearn.metrics import confusion_matrix
# show the classification report for the model
from sklearn.metrics import classification_report

y_pred_log = LogReg.predict(X)
print("Classification Report for Logistic Regression : \n", classification_report(y, y_pred_log), "\n")
print ("Confusion Matrix for Logistic Regression : \n", confusion_matrix(y, y_pred_log), "\n")

y_pred_gnb = gnb.predict(X)
print("Classification Report for Gaussian Naive Bayes : \n", classification_report(y, y_pred_gnb), "\n")
print ("Confusion Matrix for Gaussian Naive Bayes : \n", confusion_matrix(y, y_pred_gnb), "\n")




Classification Report for Logistic Regression : 
               precision    recall  f1-score   support

           0       0.90      0.99      0.94     39922
           1       0.67      0.17      0.27      5289

    accuracy                           0.89     45211
   macro avg       0.79      0.58      0.61     45211
weighted avg       0.87      0.89      0.86     45211
 

Confusion Matrix for Logistic Regression : 
 [[39489   433]
 [ 4404   885]] 

Classification Report for Gaussian Naive Bayes : 
               precision    recall  f1-score   support

           0       0.91      0.91      0.91     39922
           1       0.31      0.32      0.32      5289

    accuracy                           0.84     45211
   macro avg       0.61      0.62      0.61     45211
weighted avg       0.84      0.84      0.84     45211
 

Confusion Matrix for Gaussian Naive Bayes : 
 [[36190  3732]
 [ 3577  1712]] 

